



### Numpy Basics

In [1]:
a = 4+5j
a


(4+5j)

In [2]:
type(a)

complex

In [4]:
fruit = "This is is fruit"
fruit

'This is is fruit'

In [5]:
fruit.find('is')

2

In [6]:
fruit.count('is')

3

In [7]:
tup1 = (1,2,3)
tup2 = (4,5,6)
tup1,tup2

((1, 2, 3), (4, 5, 6))

In [10]:
 tup3 = tup1+tup2

In [12]:
tup3

(1, 2, 3, 4, 5, 6)

In [13]:
min(tup3)

1

In [14]:
max(tup3)

6

In [15]:
tup4 = (1,2,3,4,'add','sub','division')

In [16]:
min(tup4)

TypeError: '<' not supported between instances of 'str' and 'int'

## Numpy 

In [1]:
#numpy
import numpy as np
l1 = [10,20,30,40] # l1 is list
ar1 = np.array(l1)
ar1 #ar1 is numpy array

array([10, 20, 30, 40])

In [2]:
ar1

array([10, 20, 30, 40])

In [5]:
l2 = [20,30,40,50,60]
ar2 = np.array([l2,l1])
ar2

array([list([20, 30, 40, 50, 60]), list([10, 20, 30, 40])], dtype=object)

In [8]:
ar2[1][3]

40

In [9]:
type(ar1)

numpy.ndarray

In [10]:
type(ar2)

numpy.ndarray

In [15]:
#initializing numpy array with zeros
import numpy as np
n1 = np.zeros((3,4)) #3 rows and 4 columns
#zeros to fill with zeros all values of array
n1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
n2 =  np.full((3,4),2) # 3 rows 4 columns and 2 is value
n2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [17]:
n3 = np.full((3,4),0)
#can be implemented using np.zeros()
n3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
# range in numpy
n4 = np.arange(10,35) 
#10 is starting range and 35 is end but it is exclusive(not included)
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [25]:
n5 = np.arange(11,20,2) #2 is step
n5

array([11, 13, 15, 17, 19])

In [29]:
n6 = np.random.randint(2,100,20)
n6

array([48,  3, 58, 80, 66, 36, 14, 87, 94, 54,  6, 63, 56, 24, 52, 50, 28,
       66, 73,  9])

In [30]:
n3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [32]:
n5

array([11, 13, 15, 17, 19])

In [33]:
n7= np.array([[1,2,3],[4,5,6]]) #2 rows and 3 column
n7

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
#shape is used for rows and column and also changing them
n7.shape

(2, 3)

In [36]:
n7.shape = (3,2)
n7.shape

(3, 2)

In [37]:
n7

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
#joining two arrays 
# 1. vstack() == vertical stack to add arrays vertically
# 2. hstack() == horizontal stack to add arrays horizontaly
# 3. column_stack == to add arrays according to column

In [44]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
#dimension should be same or else error 
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [45]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [42]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [46]:
n1 = np.array([10,20,30,40,70])
n2 = np.array([50,40,60,10])
# intersection
np.intersect1d(n1,n2)

array([10, 40])

In [49]:
np.intersect1d(n2,n1)

array([10, 40])

In [50]:
# set difference 
np.setdiff1d(n1,n2)

array([20, 30, 70])

In [52]:
np.setdiff1d(n2,n1)

array([50, 60])

In [56]:
#add arrays 
n1 = np.array([10,20])
n2 = np.array([30,40])
#adding all elements of list
np.sum([n1])


30

In [57]:
np.sum([n1,n2])

100

In [58]:
#addition is done coloumnwise
np.sum([n1,n2],axis=0)


array([40, 60])

In [59]:
#addition is done row wise
np.sum([n1,n2],axis = 1)

array([30, 70])

In [65]:
# basic operations
n1 = np.array([10,20,30])
n1 = n1-1
# 1 is subtracted from all elements of n1 
n1

array([ 9, 19, 29])

In [66]:
n1 =  n1*2
n1

array([18, 38, 58])

In [67]:
n1 = n1+2
n1

array([20, 40, 60])

In [68]:
n1 =  n1 / 2
n1

array([10., 20., 30.])

In [72]:
# mean median and standard deviation
n1 = np.array([10,20,30])
np.mean(n1)

20.0

In [73]:
np.median(n1)

20.0

In [74]:
#standard deviation
np.std(n1)

8.16496580927726

In [75]:
#saving and loading array 
n1 = np.array([10,20,30,40,50])
np.save('my_array1',n1)

In [76]:
#it is stored in location where ipynb file is stored
n2 = np.load('my_array1.npy')
n2

array([10, 20, 30, 40, 50])